### ISSUE TITLE
User authentication

### ISSUE THREAD

**Issue by AdrianoLMRS** [AdrianoLMRS/Website#3]
# 🛡️ Authentication

## 📝 Description
The application requires users to authenticate before proceeding to payment with Stripe. This ensures secure transactions and personalized access.

## 🔧 Requirements
1. **Login System**:  
   Implement a user login system using secure authentication methods.
   
2. **Stripe Integration**:  
   Ensure Stripe payments are only accessible to authenticated users.

## 📋 Tasks
- [x] Create a login page and integrate it with the backend authentication API.
- [x] Add middleware to restrict access to the payment flow for non-authenticated users.
- [x] #4
- [x] Provide appropriate error messages for unauthenticated access attempts.

## 🖼️ Flow Diagram
```mermaid
flowchart TD
    Start[Start] --> |Unauthenticated| Login[Login Page]
    Login --> |Authenticated| Payment[Stripe Payment Page]
    Payment --> Success[Payment Success]
    Payment --> Failure[Payment Failure]

**Comment by AdrianoLMRS** [comment]
Integrate with 0auth

**Comment by AdrianoLMRS** [comment]
Auth0 already integrated with commit [0Auth integrated in /login](https://github.com/AdrianoLMRS/Website/commit/44862ce8486fcc748f220df71807c2c3cb8e7940).

New issue : #4
