### ISSUE TITLE
Integrate Auth0 with Stripe

### ISSUE THREAD

**Issue by AdrianoLMRS** [AdrianoLMRS/Website#4]
# Integrate Auth0 with Stripe

## Summary

The goal is to link the already integrated **Auth0** authentication with **Stripe** to enable authenticated users to make payments seamlessly.

## Tasks

- Link Auth0 user authentication to the Stripe checkout session.
- Ensure that after successful login, users can proceed to Stripe for payments.
- Store user data (if not already done) in MongoDB after authentication.

## Acceptance Criteria

- [ ] Stripe checkoout only with Auth0 logged users.
- [ ] User data is stored in MongoDB after authentication.
- [ ] Payments are processed successfully through Stripe for authenticated users.

## Resources

- [Auth0 Docs](https://auth0.com/docs)
- [Stripe Docs](https://stripe.com/docs)

**Comment by AdrianoLMRS** [comment]
Auth0 plan failed, Auth0 does not suport MongoDB atlas and its so complicated to integrate with the database, creating JWT authentication without any API may be the best choice.
